### ISSUE TITLE
After sending image cannot revert back to 'normal' wLED without rebooting

### ISSUE THREAD

**Issue by withanhdammit** [werkstrom/WLED-PixelArtConverter#10]
wLED 0.14.0-b5
pixart 1.0.8 and 1.1.0

After uploading an image to my matrix, if I want to return to a 'normal' wLED effect, I have to reboot my controller.
I have tried this with both the stable 1.0.8 as well as 1.1.0 with a similar result.

**Comment by withanhdammit** [comment]
I figured out a work-around.  I created a preset and if I select the preset after it loads I can then go back to using any of the normal options.

**Comment by werkstrom** [comment]
This should be raised as a WLED issue, (if it is not by design, which it may be) as PixelArtConverter only uses WLED's built in functionality to show the image.
