### ISSUE TITLE
I can't get the images to show up

### ISSUE THREAD

**Issue by Boaztheostrich** [werkstrom/WLED-PixelArtConverter#2]
I have been unable to get any of my images to clearly display on my 32x16 matrix.

I have attached one of the images below the matrix is serpentine starting at the top left, I have it set as such in the WLED settings and scrolling text from WLED displays properly.

Any help would be greatly appreciated.
![pixil-frame-0 (3)](https://user-images.githubusercontent.com/81034456/219277569-3bef672c-c67d-47d6-bb43-a945cccce3f0.png)
![image](https://user-images.githubusercontent.com/81034456/219277668-9b4fdb4a-505c-4f0d-8988-b1ed0f52248b.png)
I am using the direct upload with these settings:

![image](https://user-images.githubusercontent.com/81034456/219277850-c1bbaf42-227f-47f9-9cf2-45320bccbdbf.png)

I have tried all the options for the led setup and none have worked for me, I have also tried creating a preset with the copy pasted values but I keep getting this error:

![image](https://user-images.githubusercontent.com/81034456/219278069-1a00d7a6-1dcb-42c8-b4fa-c364b35897a4.png)

Thanks!

**Comment by Boaztheostrich** [comment]
I was able to get some images to work using these settings

![image](https://user-images.githubusercontent.com/81034456/219436297-264a9399-5cb8-4f83-a507-9e20e32c8403.png)
I cannot get this image to work
![pixil-frame-0 (2)](https://user-images.githubusercontent.com/81034456/219436406-8e371d4e-5343-4236-b590-c6d11df39f1d.png)

Another issue I am having is when I adjust brightness in WLED some of the colors disappear.

**Comment by werkstrom** [comment]
You could perhaps supply some JSON, Screenshots really does not tell the story :) Also, which version are you running. And thirdly, did you try to upload the code directly from the tool, should be much easier than copy/paste.

**Comment by werkstrom** [comment]
Also the matrix need to match the led-setup-page. Perhaps you could supply that as well

**Comment by Boaztheostrich** [comment]
Here is the JSON:

{"on":true,"bri":128,"seg":{"id":0,"i":[0,'ff7e00','9299ae','757c98','666c88','ff7e00','616679',6,11,'000000','ff7e00',12,17,'000000','7d849c','848ca8','8790b7','8188b1','ff7e00','747ea6',23,26,'ff7e00','877072','7e6666','ff7e00','e9d0d0','fefcfc','ffffff','9095aa','7e849f','606a89','515876','4b526b',37,39,'000000','ff7e00','000000',41,43,'ff7e00',43,46,'000000','ff7e00','000000','585f7e','000000','656a8c','6d729a','ff7e00','6a6c98',54,58,'ff7e00','71474f','ff7e00','974a4c',61,63,'ff7e00','ffffff',64,67,'ff7e00','303b56',68,72,'ff7e00','000000',73,78,'ff7e00',78,80,'000000','ff7e00','000000','464465','524972','ff7e00','594b7d',86,92,'ff7e00','8d161b','511012',94,96,'ff7e00','565a6a','45495d','ff7e00','1a2036','14192d','ff7e00','000000',103,106,'ff7e00','000000','ff7e00','000000','ff7e00','000000',111,113,'ff7e00','000000','352746','000000',116,124,'ff7e00','730e11',125,127,'ff7e00','aeaeae',128,132,'ff7e00',132,134,'000000','ff7e00',135,137,'000000','ff7e00','000000','ff7e00','000000',141,144,'ff7e00',144,149,'000000','ff7e00','6b2e5d',151,158,'ff7e00','453e3e','c1c1c1','444647','333b3b',162,164,'ff7e00',164,169,'000000',169,171,'ff7e00','000000',172,174,'ff7e00','000000',175,179,'ff7e00',179,181,'000000','ff7e00','000000',183,188,'ff7e00','2b0a0a','291b1c','ff7e00','999999','444646','ff7e00',194,196,'000000','ff7e00',197,201,'000000','ff7e00','000000',203,205,'ff7e00',205,209,'000000','ff7e00','000000','ff7e00','000000',213,215,'ff7e00','000000','ff7e00','681628','ff7e00','310a0e','1e0b0e','ff7e00','535252','838383',224,227,'ff7e00',227,229,'000000','ff7e00',230,235,'000000','ff7e00','000000',237,240,'ff7e00','06090e',241,243,'000000',243,246,'ff7e00',246,250,'000000','ff7e00','2e0d11','ff7e00','292525','504f4f','6f6f6f',256,258,'ff7e00','000000','ff7e00','000000','ff7e00',262,264,'000000','ff7e00',265,267,'000000','ff7e00','000000','ff7e00',270,273,'000000','ff7e00',274,276,'000000',276,278,'ff7e00',278,280,'000000',280,283,'ff7e00','310e15',284,286,'ff7e00','514f4f','696869',288,290,'ff7e00',290,292,'000000',292,296,'ff7e00','000000',297,300,'ff7e00','000000','ff7e00','000000',303,305,'ff7e00',305,307,'000000',307,310,'ff7e00',310,314,'000000','ff7e00','381216',316,319,'ff7e00','6b6a6a','ff7e00','000000',322,325,'ff7e00',325,327,'000000','ff7e00','000000',329,331,'ff7e00',331,334,'b5a5d5','000000','ff7e00','b5a5d5',337,341,'000000',341,345,'ff7e00',345,347,'000000',347,350,'ff7e00','5e5859','747373','000000','3a433d',354,358,'ff7e00',358,361,'000000','ff7e00',362,366,'b5a5d5','000000','ff7e00',368,374,'000000',374,376,'ff7e00','000000','ff7e00','000000',379,382,'ff7e00','66605e','7f7c7c',384,386,'ff7e00',386,389,'000000','ff7e00','000000','ff7e00',392,395,'000000','b5a5d5','13361d',397,399,'b5a5d5','000000','b5a5d5',401,403,'000000','b5a5d5','36442c',405,409,'ff7e00','000000','ff7e00','68351c','553425','ff7e00','6f6a69','8c8989',416,418,'000000',418,420,'ff7e00',420,425,'000000',425,427,'b5a5d5','000000','30523a','b5a5d5',430,432,'000000','b5a5d5',433,439,'000000',439,446,'ff7e00','86817d','a09e9c','ff7e00','000000',450,453,'ff7e00','000000','ff7e00','000000','b5a5d5','000000',458,460,'b5a5d5','5a7662',461,463,'b5a5d5','53725b',464,466,'b5a5d5','000000','b5a5d5','000000','827256',470,472,'000000','ff7e00','000000','ff7e00','a47755','8e735e','8e8177','a19d9a','bebebc','dcdcdc','000000','ff7e00',483,489,'000000',489,492,'b5a5d5','7f9382','7f8f83','7b8c82','b5a5d5','000000','90bc9d','000000','b5a5d5',500,502,'000000','b08d6b',503,506,'000000','ce9c73','b99475','a38f7c','ada29a','c4c1bf','dadada']}}

 I tried on v 1.0.5 and 1.0.6 
 
 The matrix matches the LED-setup page it is just a 32x16 matrix and other 32x16 images work with it.
 
 Thanks for the response.

**Comment by werkstrom** [comment]
JSON appears valid, are you running the official b1? As stated in the read.me there are issues with it, and it also appears the copy/paste does not work all of the time. Did you try uploading directly? On the brightness... That's is how WLED works. Since it does not preserve the original values when changing brightness, color information is lost. Unfortunate, but I can understand the reason from a WLED perspective. I did raise an issue, but got a good explanation on why it is like it is.

**Comment by werkstrom** [comment]
Use 1.0.8. Hopefully works better. Also you should probably try with the latest nightly as there are issues with the original b1-release of WLED. All known issues are fixed in WLED, but only available in nightly builds until b2 is released.
